# Generated by Django 2.0.7 on 2018-08-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugorders',
            old_name='drug_order_id',
            new_name='pcc_drug_order_id',
        ),
    ]
