# Generated by Django 2.0.7 on 2018-08-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcc', '0002_auto_20180802_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugorders',
            old_name='BPD_value',
            new_name='BP_value',
        ),
        migrations.AddField(
            model_name='drugorders',
            name='BP_vitals_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
