# Generated by Django 2.0.7 on 2018-08-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcc', '0003_auto_20180802_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugorders',
            options={'verbose_name': 'Drug Orders', 'verbose_name_plural': 'Drug Orders'},
        ),
    ]
