# Generated by Django 2.0.7 on 2018-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcc', '0004_auto_20180806_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
