# Generated by Django 2.0.7 on 2018-07-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotPreferred',
            fields=[
                ('not_preferred_drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('NDC', models.CharField(blank=True, max_length=255, null=True)),
                ('not_preferred_drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Not Preferred Drug',
                'verbose_name_plural': 'Not Preferred Drugs',
                'ordering': ['not_preferred_drug_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('non_preferred_drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.NotPreferred')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred',
            fields=[
                ('preferred_drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('NDC', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('not_preferred', models.ManyToManyField(related_name='not_preferred', to='recommendation.NotPreferred')),
            ],
            options={
                'verbose_name': 'Preferred Drug',
                'verbose_name_plural': 'Preferred Drugs',
                'ordering': ['preferred_drug_name'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='preferred_drug_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.Preferred'),
        ),
    ]
