# Generated by Django 2.0.7 on 2018-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False)),
                ('non_preferred_ndc', models.CharField(blank=True, max_length=25, null=True)),
                ('non_preferred_drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('non_preferred_pharma_class', models.CharField(blank=True, max_length=255, null=True)),
                ('non_preferred_cost_month', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_ndc', models.CharField(blank=True, max_length=25, null=True)),
                ('recommended_drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_pharma_class', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_cost_month', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
