# Generated by Django 2.0.7 on 2018-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonpreferred',
            name='preferred',
        ),
        migrations.RemoveField(
            model_name='preferred',
            name='notes2',
        ),
        migrations.AddField(
            model_name='preferred',
            name='non_preferred',
            field=models.ManyToManyField(through='recommendation.Position', to='recommendation.NonPreferred'),
        ),
    ]
