# Generated by Django 2.0.7 on 2018-07-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferred',
            name='not_preferred',
            field=models.ManyToManyField(to='recommendation.NotPreferred'),
        ),
    ]
