# Generated by Django 2.0.7 on 2018-07-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='non_preferred_cost_month',
            new_name='non_preferred_cost',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='recommended_cost_month',
            new_name='recommended_cost',
        ),
    ]
