# Generated by Django 2.0.7 on 2018-07-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20180725_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPreferred',
            fields=[
                ('non_preferred_drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndc', models.CharField(blank=True, max_length=25, null=True)),
                ('drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_cost', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Not Preferred Drug',
                'verbose_name_plural': 'Not Preferred Drugs',
            },
        ),
        migrations.CreateModel(
            name='Preferred',
            fields=[
                ('preferred_drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndc', models.CharField(blank=True, max_length=25, null=True)),
                ('drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_priority', models.IntegerField(blank=True, null=True)),
                ('non_preferred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.NonPreferred')),
            ],
            options={
                'verbose_name': 'Preferred Drug',
                'verbose_name_plural': 'Preferred Drugs',
            },
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
