# Generated by Django 2.0.7 on 2018-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20180727_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferred',
            name='non_preferred',
        ),
        migrations.AddField(
            model_name='preferred',
            name='preferred',
            field=models.ManyToManyField(to='recommendation.NonPreferred'),
        ),
    ]
