# Generated by Django 2.0.7 on 2018-07-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20180727_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferred',
            old_name='preferred',
            new_name='not_preferred',
        ),
    ]
