# Generated by Django 2.0.7 on 2018-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20180725_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonpreferred',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferred',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
