# Generated by Django 2.0.7 on 2018-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20180725_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpreferred',
            name='ndc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preferred',
            name='ndc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
