# Generated by Django 2.0.7 on 2018-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20180727_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferred',
            name='not_preferred',
            field=models.ManyToManyField(related_name='not_preferred', to='recommendation.NonPreferred'),
        ),
    ]
