# Generated by Django 2.0.7 on 2018-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20180726_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonpreferred',
            options={'ordering': ['drug_name'], 'verbose_name': 'Not Preferred Drug', 'verbose_name_plural': 'Not Preferred Drugs'},
        ),
        migrations.AlterModelOptions(
            name='preferred',
            options={'ordering': ['drug_name'], 'verbose_name': 'Preferred Drug', 'verbose_name_plural': 'Preferred Drugs'},
        ),
        migrations.RemoveField(
            model_name='preferred',
            name='non_preferred',
        ),
        migrations.AddField(
            model_name='nonpreferred',
            name='preferred',
            field=models.ManyToManyField(to='recommendation.Preferred'),
        ),
    ]
