# Generated by Django 2.0.7 on 2018-07-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20180727_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='preferred',
            name='preferred_priority',
        ),
        migrations.AddField(
            model_name='position',
            name='preferred',
            field=models.ManyToManyField(to='recommendation.Preferred'),
        ),
    ]
