# Generated by Django 2.0.7 on 2018-07-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20180727_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='preferred',
        ),
        migrations.AddField(
            model_name='position',
            name='preferred_drug_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.Preferred'),
        ),
    ]
