# Generated by Django 2.0.7 on 2018-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('medispan_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndc_upc_hri', models.CharField(max_length=11)),
                ('rx_otc_indicator_code', models.CharField(max_length=1)),
                ('drug_descriptor_identifier', models.IntegerField()),
                ('generic_product_identifier', models.CharField(max_length=14)),
                ('price_code', models.CharField(max_length=1)),
                ('effective_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit_price_extended', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('awp_indicator_code', models.CharField(max_length=1)),
                ('transaction_code', models.CharField(max_length=1)),
                ('last_change_date', models.DateField()),
                ('drug_name', models.CharField(max_length=30)),
                ('route_of_administration', models.CharField(max_length=2)),
                ('dosage_form', models.CharField(max_length=4)),
                ('strength', models.CharField(max_length=15)),
                ('strength_unit_of_measure', models.CharField(max_length=10)),
                ('bioequivalence_code', models.CharField(max_length=1)),
            ],
        ),
    ]
