# Generated by Django 2.0.7 on 2018-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medispan', '0002_auto_20180717_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='ndc_upc_hri',
            field=models.CharField(max_length=25),
        ),
    ]
