# Generated by Django 2.0.7 on 2018-08-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medispan', '0005_drug_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='test_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
