# Generated by Django 2.0.7 on 2018-08-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medispan', '0006_drug_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='test_field',
        ),
    ]
