# Generated by Django 2.0.7 on 2018-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugOrders',
            fields=[
                ('drug_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('phys_order_id', models.IntegerField(blank=True, null=True)),
                ('patient_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_census_id', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('reorder', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('MAR_start_date', models.DateTimeField(blank=True, null=True)),
                ('MAR_end_date', models.DateTimeField(blank=True, null=True)),
                ('order_hold_start_date', models.DateTimeField(blank=True, null=True)),
                ('order_hold_end_date', models.DateTimeField(blank=True, null=True)),
                ('discontinued_date', models.DateTimeField(blank=True, null=True)),
                ('order_created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order_created_date', models.DateTimeField(blank=True, null=True)),
                ('order_created_by_user_long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_revision_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order_revision_by_date', models.DateTimeField(blank=True, null=True)),
                ('physician_id', models.IntegerField(blank=True, null=True)),
                ('physician_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('PRN', models.CharField(blank=True, max_length=100, null=True)),
                ('pharmacy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_category_id', models.IntegerField(blank=True, null=True)),
                ('order_category', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type_id', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_method', models.CharField(blank=True, max_length=100, null=True)),
                ('order_description', models.CharField(blank=True, max_length=100, null=True)),
                ('related_generic', models.CharField(blank=True, max_length=100, null=True)),
                ('advanced_directive', models.CharField(blank=True, max_length=100, null=True)),
                ('pharmacy_medication_name', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('strength_UOM', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_supplement', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_type_id', models.IntegerField(blank=True, null=True)),
                ('diet_texture', models.CharField(blank=True, max_length=100, null=True)),
                ('fluid_consistency', models.CharField(blank=True, max_length=100, null=True)),
                ('route_of_admin', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_to_administer', models.CharField(blank=True, max_length=100, null=True)),
                ('directions', models.CharField(blank=True, max_length=100, null=True)),
                ('related_diagnoses', models.CharField(blank=True, max_length=100, null=True)),
                ('indications_for_use', models.CharField(blank=True, max_length=100, null=True)),
                ('nurse_admin_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('wt_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('resp_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('BPV_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('pulse_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('BS_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('O2_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('ht_vital', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vitals_description', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('BPD_value', models.CharField(blank=True, max_length=100, null=True)),
                ('BPD_diastolic_value', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('allergy', models.CharField(blank=True, max_length=100, null=True)),
                ('NCSP_pho_phys_order', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
